-- AlterTable
ALTER TABLE `columnselection` MODIFY `Title` BOOLEAN NULL,
    MODIFY `Description` BOOLEAN NULL,
    MODIFY `Vendor` BOOLEAN NULL,
    MODIFY `Tags` BOOLEAN NULL,
    MODIFY `CustomType` BOOLEAN NULL,
    MODIFY `Images` BOOLEAN NULL,
    MODIFY `Status` BOOLEAN NULL,
    MODIFY `PublishedOnStore` BOOLEAN NULL,
    MODIFY `Variants` BOOLEAN NULL,
    MODIFY `VariantDeletion` BOOLEAN NULL,
    MODIFY `Metafields` BOOLEAN NULL,
    MODIFY `Category` BOOLEAN NULL,
    MODIFY `InventoryLevel` BOOLEAN NULL,
    MODIFY `Price` BOOLEAN NULL,
    MODIFY `CompareAtPrice` BOOLEAN NULL,
    MODIFY `CostPerItem` BOOLEAN NULL,
    MODIFY `HSCode` BOOLEAN NULL,
    MODIFY `CountryRegion` BOOLEAN NULL,
    MODIFY `TrackInventory` BOOLEAN NULL,
    MODIFY `InventoryPolicy` BOOLEAN NULL,
    MODIFY `Weight` BOOLEAN NULL,
    MODIFY `WeightUnit` BOOLEAN NULL,
    MODIFY `Taxable` BOOLEAN NULL,
    MODIFY `Position` BOOLEAN NULL,
    MODIFY `Options` BOOLEAN NULL,
    MODIFY `SKU` BOOLEAN NULL,
    MODIFY `Barcode` BOOLEAN NULL;
