# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3e416bacdd36ded2b7c6a8faae1dc77c"
name = "inventory-sync"
handle = "inventory-sync-70"
application_url = "https://pharmacology-l-competitive-birmingham.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "siar-development.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_locations,read_products,write_inventory,write_products,write_publications,read_publications"

[auth]
redirect_urls = [
  "https://pharmacology-l-competitive-birmingham.trycloudflare.com/auth/callback",
  "https://pharmacology-l-competitive-birmingham.trycloudflare.com/auth/shopify/callback",
  "https://pharmacology-l-competitive-birmingham.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
