# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b6660fd53f9d08065cf7714aacb52c15"
name = "inventory-sync"
handle = "inventory-sync-69"
application_url = "https://example.com/"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,write_inventory,read_products,write_products,read_locations,read_inventory"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
