-- CreateTable
CREATE TABLE `ColumnSelection` (
    `shop` VARCHAR(191) NOT NULL,
    `Title` BOOLEAN NOT NULL,
    `Description` BOOLEAN NOT NULL,
    `Vendor` BOOLEAN NOT NULL,
    `Tags` BOOLEAN NOT NULL,
    `CustomType` BOOLEAN NOT NULL,
    `Images` BOOLEAN NOT NULL,
    `ThemeTemplate` BOOLEAN NOT NULL,
    `Status` BOOLEAN NOT NULL,
    `PublishedOnStore` BOOLEAN NOT NULL,
    `Variants` BOOLEAN NOT NULL,
    `VariantDeletion` BOOLEAN NOT NULL,
    `Metafields` BOOLEAN NOT NULL,
    `Category` BOOLEAN NOT NULL,
    `InventoryLevel` BOOLEAN NOT NULL,
    `Price` BOOLEAN NOT NULL,
    `CompareAtPrice` BOOLEAN NOT NULL,
    `CostPerItem` BOOLEAN NOT NULL,
    `HSCode` BOOLEAN NOT NULL,
    `CountryRegion` BOOLEAN NOT NULL,
    `TrackInventory` BOOLEAN NOT NULL,
    `InventoryPolicy` BOOLEAN NOT NULL,
    `Weight` BOOLEAN NOT NULL,
    `WeightUnit` BOOLEAN NOT NULL,
    `Taxable` BOOLEAN NOT NULL,
    `Position` BOOLEAN NOT NULL,
    `Options` BOOLEAN NOT NULL,
    `SKU` BOOLEAN NOT NULL,
    `Barcode` BOOLEAN NOT NULL,

    PRIMARY KEY (`shop`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
